apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-webapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/revanthvermareddy/argocd-app-config.git
    targetRevision: HEAD
    path: helm-webapp
  destination: 
    server: https://kubernetes.default.svc
    namespace: helm-webapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
